import { describe, it, expect } from 'vitest';
import {
  branchNameForJob,
  buildClaudePrompt,
  parseClaudeResultBlock,
  RESULT_JSON_HEADING,
  renderPrBody,
  truncate,
} from '../src/prompt.js';
import { parsePrNumber } from '../src/job-handler.js';
import type { DevJob } from '../src/types.js';

function fakeJob(overrides: Partial<DevJob> = {}): DevJob {
  const base: DevJob = {
    id: '8a3f0b21-0000-0000-0000-000000000000',
    workspace_id: 'ws',
    agent_id: 'agent',
    session_id: null,
    user_id: 'user',
    task_spec: 'Build a counter module in TypeScript with vitest tests.',
    target_repo: 'whitey861/roost-test',
    target_branch: 'main',
    agent_provider: 'claude_code',
    agent_provider_config: {},
    max_iterations: 50,
    max_cost_usd: 5,
    max_runtime_minutes: 120,
    status: 'queued',
    leased_by: null,
    leased_at: null,
    lease_expires_at: null,
    branch_name: null,
    pr_url: null,
    pr_number: null,
    files_changed: null,
    tests_passed: null,
    tests_summary: null,
    cost_usd: null,
    iterations_used: null,
    runtime_seconds: null,
    agent_summary: null,
    worker_log: null,
    error_message: null,
    created_at: '2025-05-09T00:00:00Z',
    updated_at: '2025-05-09T00:00:00Z',
    completed_at: null,
  };
  return { ...base, ...overrides };
}

describe('buildClaudePrompt', () => {
  it('embeds the task spec, branch, and budget caps', () => {
    const p = buildClaudePrompt(fakeJob());
    expect(p).toContain('Build a counter module');
    expect(p).toContain('branch `main`');
    expect(p).toContain('Max cost: $5.00');
    expect(p).toContain('Max runtime: 120 minutes');
    expect(p).toContain(RESULT_JSON_HEADING);
  });

  it('uses the requested base branch when overridden', () => {
    const p = buildClaudePrompt(fakeJob({ target_branch: 'develop' }));
    expect(p).toContain('branch `develop`');
  });
});

describe('parseClaudeResultBlock', () => {
  it('parses a well-formed result block', () => {
    const stdout = `
Some leading log lines.
${RESULT_JSON_HEADING}
\`\`\`json
{
  "prTitle": "Add counter module",
  "prBody": "Body text here.",
  "commitMessage": "feat: counter module",
  "filesChanged": 3,
  "summary": "Built counter with 100% coverage.",
  "testCommand": "npm test",
  "iterations": 4,
  "cost_usd": 1.25
}
\`\`\`
`;
    const parsed = parseClaudeResultBlock(stdout);
    expect(parsed).not.toBeNull();
    expect(parsed?.prTitle).toBe('Add counter module');
    expect(parsed?.testCommand).toBe('npm test');
    expect(parsed?.cost_usd).toBe(1.25);
    expect(parsed?.filesChanged).toBe(3);
  });

  it('returns null when the JSON is missing', () => {
    expect(parseClaudeResultBlock('hello world')).toBeNull();
  });

  it('returns null when JSON is malformed', () => {
    const stdout = `${RESULT_JSON_HEADING}\n\`\`\`json\n{ this isn't json\n\`\`\``;
    expect(parseClaudeResultBlock(stdout)).toBeNull();
  });

  it('coerces missing optional fields to safe defaults', () => {
    const stdout = `${RESULT_JSON_HEADING}\n\`\`\`json\n{"prTitle":"t","prBody":"b"}\n\`\`\``;
    const parsed = parseClaudeResultBlock(stdout)!;
    expect(parsed.commitMessage).toBe('t');
    expect(parsed.testCommand).toBeNull();
    expect(parsed.filesChanged).toBe(0);
    expect(parsed.cost_usd).toBe(0);
  });

  it('returns null when prTitle is empty (treats as malformed)', () => {
    const stdout = `${RESULT_JSON_HEADING}\n\`\`\`json\n{"prTitle":""}\n\`\`\``;
    expect(parseClaudeResultBlock(stdout)).toBeNull();
  });
});

describe('branchNameForJob', () => {
  it('produces a stable short branch name from the uuid prefix', () => {
    const id = '8a3f0b21-1234-5678-9abc-def012345678';
    expect(branchNameForJob(id)).toBe('roost-job-8a3f0b21');
  });
});

describe('renderPrBody', () => {
  it('appends a Roost attribution footer with the job id', () => {
    const body = renderPrBody('Original body.', 'job-xyz');
    expect(body).toContain('Original body.');
    expect(body).toContain('Generated by the Roost dev agent');
    expect(body).toContain('job-xyz');
  });
});

describe('truncate', () => {
  it('passes through short strings', () => {
    expect(truncate('hi', 10)).toBe('hi');
  });
  it('clips with an ellipsis when over the limit', () => {
    expect(truncate('abcdefghij', 6)).toBe('abcde…');
  });
});

describe('parsePrNumber', () => {
  it('extracts the integer from a github PR URL', () => {
    expect(parsePrNumber('https://github.com/whitey861/roost-test/pull/42')).toBe(42);
  });
  it('returns null when the URL has no pull/N segment', () => {
    expect(parsePrNumber('https://example.com')).toBeNull();
  });
});
