// Build the prompt fed to Claude Code for a dev job. Pure function: takes
// the job spec, returns a markdown string. We keep this pure so it can be
// unit-tested without touching disk or processes.

import type { DevJob } from './types.js';

export const RESULT_JSON_HEADING = '## ROOST_RESULT_JSON';

export function buildClaudePrompt(job: DevJob): string {
  const branch = job.target_branch ?? 'main';
  return `# Roost dev agent task

You are running headlessly inside a Roost worker. The repo at the current working
directory has already been cloned at branch \`${branch}\` and a fresh feature
branch is checked out for you. Make your changes there.

## Task

${job.task_spec}

## Standing instructions

- Run tests after each substantive change. Iterate until tests pass.
- Keep the diff minimal. Don't refactor surrounding code unless the task asks for it.
- If the repo doesn't already have a test runner that covers your changes, add one
  appropriate for the language and framework already in use.
- Commit your work in logical chunks. The worker will combine commits as needed
  before pushing.
- If you can't complete the task, push what you have, label the PR clearly, and
  explain in the PR body what blocked you.

## Budget and limits

- Max cost: $${formatBudget(job.max_cost_usd)}
- Max runtime: ${job.max_runtime_minutes ?? 120} minutes
- Max iterations: ${job.max_iterations ?? 50}

## Output format

When you are done (whether the task completed or you hit a stop condition),
output a single fenced JSON block with this shape under the heading
\`${RESULT_JSON_HEADING}\`:

${RESULT_JSON_HEADING}
\`\`\`json
{
  "prTitle": "Short PR title (under 70 chars)",
  "prBody": "Markdown body: summary, test status, caveats.",
  "commitMessage": "Single-line commit message used if no commits were made yet.",
  "filesChanged": 0,
  "summary": "One-paragraph plain-English summary for the user.",
  "testCommand": "shell command the worker should run to verify, or null",
  "iterations": 0,
  "cost_usd": 0
}
\`\`\`

The worker parses this block to populate the dev_jobs row and the PR. Don't
omit it. If a field doesn't apply, use null or 0; don't drop the key.
`;
}

function formatBudget(v: number | string | null): string {
  if (v === null || v === undefined) return '5.00';
  const n = typeof v === 'string' ? Number.parseFloat(v) : v;
  if (!Number.isFinite(n)) return '5.00';
  return n.toFixed(2);
}

// Parse the JSON block emitted by Claude Code. Returns null if the block
// can't be found or is malformed; callers fall back to a synthesised result
// in that case.
export function parseClaudeResultBlock(stdout: string): {
  prTitle: string;
  prBody: string;
  commitMessage: string;
  filesChanged: number;
  summary: string;
  testCommand: string | null;
  iterations: number;
  cost_usd: number;
} | null {
  const headingIdx = stdout.indexOf(RESULT_JSON_HEADING);
  if (headingIdx < 0) return null;
  const tail = stdout.slice(headingIdx);
  const fence = tail.match(/```(?:json)?\s*\n([\s\S]*?)\n```/);
  if (!fence || !fence[1]) return null;
  let parsed: Record<string, unknown>;
  try {
    parsed = JSON.parse(fence[1]) as Record<string, unknown>;
  } catch {
    return null;
  }
  const prTitle = typeof parsed.prTitle === 'string' ? parsed.prTitle : '';
  const prBody = typeof parsed.prBody === 'string' ? parsed.prBody : '';
  const commitMessage = typeof parsed.commitMessage === 'string' && parsed.commitMessage.length > 0
    ? parsed.commitMessage
    : prTitle || 'Roost dev agent change';
  const filesChanged = typeof parsed.filesChanged === 'number' ? Math.max(0, Math.trunc(parsed.filesChanged)) : 0;
  const summary = typeof parsed.summary === 'string' ? parsed.summary : '';
  const testCommand = typeof parsed.testCommand === 'string' && parsed.testCommand.trim().length > 0
    ? parsed.testCommand
    : null;
  const iterations = typeof parsed.iterations === 'number' ? Math.max(0, Math.trunc(parsed.iterations)) : 0;
  const cost = typeof parsed.cost_usd === 'number' ? Math.max(0, parsed.cost_usd) : 0;
  if (!prTitle) return null;
  return { prTitle, prBody, commitMessage, filesChanged, summary, testCommand, iterations, cost_usd: cost };
}

// Branch name for the dev agent's work. Short prefix + first 8 chars of
// the job UUID so it's easy to correlate in GitHub UI.
export function branchNameForJob(jobId: string): string {
  const short = jobId.replace(/-/g, '').slice(0, 8);
  return `roost-job-${short}`;
}

// Render the final PR body. We append a Roost attribution footer with the
// job id so reviewers know where the change came from.
export function renderPrBody(claudeBody: string, jobId: string): string {
  return `${claudeBody}\n\n---\nGenerated by the Roost dev agent. Job: \`${jobId}\`\n`;
}

// Clamp a string to N characters with an ellipsis if it's longer. Used for
// Telegram payloads (4096-char hard limit).
export function truncate(s: string, max: number): string {
  if (s.length <= max) return s;
  return s.slice(0, Math.max(0, max - 1)) + '…';
}
